version: '3'
services:
  service_one:
    image: 'tomcat:9'
    ports:
    - '8080:8080'
    volumes:
    - "/mnt/projects/game-of-life-nup/gameoflife-web/target/gameoflife.war : /usr/local/tomcat/webapps"
